// #define DEBUG_MATRIX_SCAN_RATE
#define TAPPING_TERM 200
#define TAPPING_TERM_PER_KEY
#undef PRINTF_FTOA_BUFFER_SIZE
#define PRINTF_FTOA_BUFFER_SIZE 64
#undef PRINTF_DISABLE_SUPPORT_EXPONENTIAL
#undef PRINTF_MAX_FLOAT
#define PRINTF_MAX_FLOAT 1e15
