#pragma once

#define MOUSEKEY_INTERVAL 16

#define MOUSEKEY_DELAY 50

#define MOUSEKEY_TIME_TO_MAX 60

#define MOUSEKEY_MAX_SPEED 4

#define MOUSEKEY_WHEEL_DELAY 0

#define MK_3_SPEED

#define COMBO_TERM_PER_COMBO